compiler: gcc
cflags: -Wall -W -pedantic -Werror -std=c11

shared:
  - name: 'experimental library argument'
    target: argument.o
    source: experimental/argument.c

  - name: 'experimental library blocks-std'
    target: blocks-std.o
    source: experimental/blocks-std.c
  
  - name: 'experimental library log'
    target: log.o
    source: experimental/log.c

  - name: 'experimental library algorithm'
    target: algorithm.o
    source: experimental/algorithm.c


programs:
  - name: 'blocks program'
    sources: blocks
    target: blocks.exe
    libs:
      - name: 'main library'
        target: blocks.o
        source: main.c
      # - name: 'compile lib'
      #   target: compile.o
      #   source: compile.c
      - name: 'execute lib'
        target: execute.o
        source: execute.c
      - name: 'clean lib'
        target: clean.o
        source: clean.c
    shared:
      - log.o
      - argument.o
      # - blocks-std.o
      - algorithm.o
   
purge:
  - '*.o'
