compiler: gcc
cflags: -Wall -W -pedantic -Werror -std=c11

shared:  
  - name: 'std library algorithm'
    target: algorithm.o
    source: std/algorithm.c

  - name: 'std library string'
    target: string.o
    source: std/string.c

  - name: 'std library string algorithm'
    target: string_algo.o
    source: std/string_algo.c

  - name: 'std library memory'
    target: memory.o
    source: std/memory.c

programs:
  # - name: 'blocks program'
  #   sources: blocks
  #   target: blocks.exe
  #   libs:
  #     - name: 'main library'
  #       target: blocks.o
  #       source: main.c
  #   shared:
  #     - algorithm.o
  #     - string.o

  - name: 'string test program'
    sources: 'std/__tests__'
    target: stringtest.exe
    libs:
      - name: 'main library'
        target: stringtest.o
        source: stringtest.c
    shared:
      - algorithm.o
      - string.o

  - name: 'string algorithm test program'
    sources: 'std/__tests__'
    target: string_algotest.exe
    libs:
      - name: 'main library'
        target: string_algotest.o
        source: string_algotest.c
    shared:
      - algorithm.o
      - string.o
      - string_algo.o

  - name: 'algorithm test program'
    sources: 'std/__tests__'
    target: algorithmtest.exe
    libs:
      - name: 'main library'
        target: algorithmtest.o
        source: algorithmtest.c
    shared:
      - algorithm.o
      - string.o

  - name: 'memory test program'
    sources: 'std/__tests__'
    target: memorytest.exe
    libs:
      - name: 'main library'
        target: memorytest.o
        source: memorytest.c
    shared:
      - memory.o

tests:
  - stringtest.exe
  - string_algotest.exe
  - algorithmtest.exe
  - memorytest.exe

purge:
  - '*.o'
